### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by chuckeles** [chuckeles/chuckeles.github.io#26]
Finish the footer, according to the current implementation. There should be links to social media, maybe a scroll-to-top button. I may also add the badges, see #25.

### Tasks

- [x] Add generic social media directive
- [x] Add links to twitter, github and codepen
- [x] Add scroll-to-top button
- [x] Consider adding the badges

**Comment by chuckeles** [comment]
Badges won't be added. The back-to-top button doesn't scroll for now, just displays a warning. I will implement this when I add some animation library.
