### ISSUE TITLE
Games card

### ISSUE THREAD

**Issue by chuckeles** [chuckeles/chuckeles.github.io#27]
It is time to add the card with my games. This shall be like any other card (#2).

### Placement

The card will be directly below the header card.

### Content

The card will contain the list of my games. These games need their own directive. They will consist primarily of an image and a title.

### Router

For all this to work, I need to employ the [ui router](https://github.com/angular-ui/ui-router).

### Tasks

- [x] Add games card
- [x] Add a placeholder game
- [x] Create some sort of a list
- [x] Add router
- [x] Configure router/states
- [x] Add tests

**Comment by chuckeles** [comment]
Closing this in favor of #28
