### ISSUE TITLE
Games

### ISSUE THREAD

**Issue by chuckeles** [chuckeles/chuckeles.github.io#28]
Here's how the game articles will work.

### Structure

Create folders content/games/space-game. This will contain all the information about the game, screens and the post.

#### Files

- *meta.json* - metadata information about the game, like name, url and screen
- *article.html* - the content of the article that will be displayed when the user clicks on the game in the list on the homepage
- *screens/* - screens from the game

### Directives

On the homepage, I will use some kind of directive, let's say gameLink. This directive will fetch relevant files, including the *meta.json* file and the main *screen.jpg* file. It will then act as a clickable image with a label.

#### Article

To achieve consistency in the game articles, I shall create special directives like gameHeader, downloadLink, screen etc.

### Template

There will also be a file content/games/template.html to quickstart a game article.

### Tasks

- [x] Add Space Game content (the files)
- [x] Add gamesList directive
- [x] Add gameLink directive
- [x] Add game state/route
- [ ] Add article directives
- [ ] Add template
- [x] Tests

**Comment by chuckeles** [comment]
:+1:

**Comment by chuckeles** [comment]
It may be actually better to have just one *meta.json* or *games.json* file.
