### ISSUE TITLE
Node server

### ISSUE THREAD

**Issue by chuckeles** [chuckeles/chuckeles.github.io#31]
I decided to move the page to heroku, so that I can change the server routes and use html5 mode in angular.

### Node

Node server will be a very simple one (#30). I'll use express and it's plugins to have a basic mostly static server. Only difference between that and github pages will be that my server will send `index.html` file when no other file matches.

### Express

The express will be set up according to [one of the older versions (v1.1.1)](https://github.com/chuckeles/chuckeles.github.io/tree/b08ed0b1ff1fe2c45375d6a161170eaed61b4653/server). Middleware:

- icons
- compress

Others like `body-parser` are not required, as the server will only send static files.

### Routes

I'll just use `express.static()` and then send `index.html` file.

### Tasks

- [x] Add dependencies to package.json
- [x] Write basic server.js
- [x] Add middleware
- [x] Add routes
- [x] Switch back to html5 mode and update urls

**Comment by chuckeles** [comment]
Simplest server ever:

```node
// requires
var express = require("express");
var compress = require("compression");

// create app
var server = express();

// add middleware
server.use(compress());

// TODO: Add sitemap.xml

// set router
server.use(express.static("./"));

// send index.html
server.get("*", function(req, res) {
  res.sendFile(__dirname + "/index.html");
});

// listen
var port = process.env.PORT || 2403;
server.listen(port, function() {
  console.log("Node server listening on port " + port);
});
```
