### ISSUE TITLE
Travis and testing

### ISSUE THREAD

**Issue by chuckeles** [chuckeles/chuckeles.github.io#6]
Use [travis ci](https://travis-ci.org/) for continuous integration and automatic testing of my code. I still need to figure out how to use it properly, but it should be possible to test HTML code for proper HTML5 markup, working links etc. It should also test javascript for errors.

### Tasks

- [x] install [karma](http://karma-runner.github.io/)
- [x] install [jasmine](http://jasmine.github.io/)
- [x] add [angular-mocks](https://docs.angularjs.org/api/ngMock)
- [x] set it up using gulp test task
- [x] write test files
- [x] test chuckeles and card directives
- [x] install [protractor](http://angular.github.io/protractor/)
- [x] set it up using gulp
- [x] write some e2e tests
- [x] set up [travis ci](https://travis-ci.org/)
- [x] verify the tests execute
- [x] celebrate :cake:

**Comment by chuckeles** [comment]
Yay! :cake: Protractor now works! Now for some tests :smiling_imp:
