### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by chuckeles** [chuckeles/chuckeles.github.io#8]
### Library

Use [GSAP](http://greensock.com/gsap) to add some cool animations to the website. Also use CSS animations. Check out [scrollmagic](http://janpaepke.github.io/ScrollMagic/), too.

### Animations

Here's some I have in my mind:
- game images and apps appearing as the user scrolls the webpage
- something on the landing page
- cool footer
- on the game post, animate images

### Tasks

- [x] Get nextCard scrolling working
- [x] Get backToTop scrolling working
- [x] Animate title and main links
- [x] Animate all the headers
- [x] Animate project links when scrolling
- [x] Animate screenshots when scrolling
- [x] Animate footer

**Comment by chuckeles** [comment]
Suggested bezier curve: [.62,.28,.23,.99](http://cubic-bezier.com/#.62,.28,.23,.99), something like the [asymmetric animation in material design](http://www.google.com/design/spec/animation/authentic-motion.html#authentic-motion-mass-weight).

**Comment by chuckeles** [comment]
Loading and animating images in: http://www.google.com/design/spec/patterns/loading-images.html
